# Generated by Django 2.0.8 on 2018-11-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_blog', '0003_auto_20181126_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nick_name',
            field=models.CharField(default='', max_length=64, verbose_name='显示名,昵称'),
        ),
    ]
