# Generated by Django 2.0.8 on 2018-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_blog', '0004_userinfo_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='', max_length=13, verbose_name='手机号'),
        ),
    ]
